Bump com.google.devtools.ksp from 1.9.23-1.0.19 to 1.9.23-1.0.20 (#388)
Bumps [com.google.devtools.ksp](https://github.com/google/ksp) from
1.9.23-1.0.19 to 1.9.23-1.0.20.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/google/ksp/releases">com.google.devtools.ksp's
releases</a>.</em></p>
<blockquote>
<h2>1.9.23-1.0.20</h2>
<h2>KSP1 issues fixed</h2>
<ul>
<li>performance optimization for certain workload consists of heavy Java
files, including
<ul>
<li>Replace IdKey's impl with identityHashCode <a
href="https://redirect.github.com/google/ksp/issues/1804">#1804</a></li>
<li>Cache enclosed descriptors by name <a
href="https://redirect.github.com/google/ksp/issues/1808">#1808</a></li>
</ul>
</li>
<li>Add excludedSources to the KSP extension object <a
href="https://redirect.github.com/google/ksp/issues/1793">#1793</a>
thanks to <a
href="https://github.com/bitspittle"><code>@​bitspittle</code></a></li>
</ul>
<h2>KSP2 issues fixed</h2>
<ul>
<li>NoClassDefFoundError for LZ4Factory when trying KSP2 <a
href="https://redirect.github.com/google/ksp/issues/1713">#1713</a></li>
<li>Calling KSType.replace() with original arguments results in <!-- raw
HTML omitted --> <a
href="https://redirect.github.com/google/ksp/issues/1807">#1807</a></li>
<li>Static fields in base class appear in derived classes <a
href="https://redirect.github.com/google/ksp/issues/1744">#1744</a></li>
<li>fix backing field checking for top level callables</li>
<li>support sealed inheritors lookup.</li>
<li>support type alias for getSymbolsWithAnnotation</li>
<li>support more types for reference elements</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/google/ksp/commit/a96538743ede1af9a6034bc24a3216871ba0d1b4"><code>a965387</code></a>
UPDATE_KOTLIN_VERSION: 1.9.23</li>
<li><a
href="https://github.com/google/ksp/commit/96361a97ace57198a786fce349c1a4380208f428"><code>96361a9</code></a>
Downgrade Kotlin to 2.0.0-Beta4</li>
<li><a
href="https://github.com/google/ksp/commit/ea7e9d2cd4e58ec1380f636ac1f2d26c36df5fbe"><code>ea7e9d2</code></a>
Revert &quot;UPDATE_KOTLIN_VERSION: 1.9.30-dev-2548&quot;</li>
<li><a
href="https://github.com/google/ksp/commit/a2b9298c147737bfe84bf0d998b64574683402e5"><code>a2b9298</code></a>
Revert &quot;UPDATE_KOTLIN_VERSION: 2.0.0-dev-4562&quot;</li>
<li><a
href="https://github.com/google/ksp/commit/cdce1978a1794d11791978406e92fbef45feab2d"><code>cdce197</code></a>
Revert &quot;Downgrade Kotlin to 2.0.0-Beta4&quot;</li>
<li><a
href="https://github.com/google/ksp/commit/4d5849a3a57c16a4a8570629cdf1a1db3935fbb3"><code>4d5849a</code></a>
Revert &quot;UPDATE_KOTLIN_VERSION: 2.0.0-Beta5&quot;</li>
<li><a
href="https://github.com/google/ksp/commit/5418453824ecf936a36805a2bd0b1e8f72f8bb6a"><code>5418453</code></a>
Remove dep to javax.annotation.ParametersAreNonnullByDefault</li>
<li><a
href="https://github.com/google/ksp/commit/70a232306ca4858e3147a799ac92d91debe8d9b1"><code>70a2323</code></a>
UPDATE_KOTLIN_VERSION: 2.0.0-Beta5</li>
<li><a
href="https://github.com/google/ksp/commit/815b7a072d5594ea87062c4c05c0f8acda3e524e"><code>815b7a0</code></a>
Keep more classes in uber jar</li>
<li><a
href="https://github.com/google/ksp/commit/acc00dda9625f31e43e8f4e26b4d51fbec885e28"><code>acc00dd</code></a>
Do not minimize lz4-java</li>
<li>Additional commits viewable in <a
href="https://github.com/google/ksp/compare/1.9.23-1.0.19...1.9.23-1.0.20">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.google.devtools.ksp&package-manager=gradle&previous-version=1.9.23-1.0.19&new-version=1.9.23-1.0.20)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>