Bump ktor from 2.3.11 to 2.3.12 (#427)
Bumps `ktor` from 2.3.11 to 2.3.12.
Updates `io.ktor:ktor-client-core` from 2.3.11 to 2.3.12
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/ktorio/ktor/releases">io.ktor:ktor-client-core's
releases</a>.</em></p>
<blockquote>
<h2>2.3.12</h2>
<blockquote>
<p>Published 20 June 2024</p>
</blockquote>
<h3>Bugfixes</h3>
<ul>
<li>NoSuchMethodError when using coroutines 1.9.0-RC (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7054">KTOR-7054</a>)</li>
<li>Server: Content-Type header for static js, css and svg resources
misses charset (<a
href="https://youtrack.jetbrains.com/issue/KTOR-6655">KTOR-6655</a>)</li>
<li>Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7016">KTOR-7016</a>)</li>
</ul>
<h3>Improvements</h3>
<ul>
<li>Update netty to 4.1.111.Final (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7094">KTOR-7094</a>)</li>
<li>Update netty due to CVE-2024-29025 (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7014">KTOR-7014</a>)</li>
<li>Update dependency on swagger (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7019">KTOR-7019</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/ktorio/ktor/blob/2.3.12/CHANGELOG.md">io.ktor:ktor-client-core's
changelog</a>.</em></p>
<blockquote>
<h1>2.3.12</h1>
<blockquote>
<p>Published 20 June 2024</p>
</blockquote>
<h3>Bugfixes</h3>
<ul>
<li>NoSuchMethodError when using coroutines 1.9.0-RC (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7054">KTOR-7054</a>)</li>
<li>Server: Content-Type header for static js, css and svg resources
misses charset (<a
href="https://youtrack.jetbrains.com/issue/KTOR-6655">KTOR-6655</a>)</li>
<li>Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7016">KTOR-7016</a>)</li>
</ul>
<h3>Improvements</h3>
<ul>
<li>Update netty to 4.1.111.Final (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7094">KTOR-7094</a>)</li>
<li>Update netty due to CVE-2024-29025 (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7014">KTOR-7014</a>)</li>
<li>Update dependency on swagger (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7019">KTOR-7019</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/ktorio/ktor/commit/c22735ce615a1b8d19499bff0a31d1efa8540fe6"><code>c22735c</code></a>
Release 2.3.12 (<a
href="https://redirect.github.com/ktorio/ktor/issues/4088">#4088</a>)</li>
<li>See full diff in <a
href="https://github.com/ktorio/ktor/compare/2.3.11...2.3.12">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.ktor:ktor-client-okhttp` from 2.3.11 to 2.3.12
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/ktorio/ktor/releases">io.ktor:ktor-client-okhttp's
releases</a>.</em></p>
<blockquote>
<h2>2.3.12</h2>
<blockquote>
<p>Published 20 June 2024</p>
</blockquote>
<h3>Bugfixes</h3>
<ul>
<li>NoSuchMethodError when using coroutines 1.9.0-RC (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7054">KTOR-7054</a>)</li>
<li>Server: Content-Type header for static js, css and svg resources
misses charset (<a
href="https://youtrack.jetbrains.com/issue/KTOR-6655">KTOR-6655</a>)</li>
<li>Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7016">KTOR-7016</a>)</li>
</ul>
<h3>Improvements</h3>
<ul>
<li>Update netty to 4.1.111.Final (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7094">KTOR-7094</a>)</li>
<li>Update netty due to CVE-2024-29025 (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7014">KTOR-7014</a>)</li>
<li>Update dependency on swagger (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7019">KTOR-7019</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/ktorio/ktor/blob/2.3.12/CHANGELOG.md">io.ktor:ktor-client-okhttp's
changelog</a>.</em></p>
<blockquote>
<h1>2.3.12</h1>
<blockquote>
<p>Published 20 June 2024</p>
</blockquote>
<h3>Bugfixes</h3>
<ul>
<li>NoSuchMethodError when using coroutines 1.9.0-RC (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7054">KTOR-7054</a>)</li>
<li>Server: Content-Type header for static js, css and svg resources
misses charset (<a
href="https://youtrack.jetbrains.com/issue/KTOR-6655">KTOR-6655</a>)</li>
<li>Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7016">KTOR-7016</a>)</li>
</ul>
<h3>Improvements</h3>
<ul>
<li>Update netty to 4.1.111.Final (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7094">KTOR-7094</a>)</li>
<li>Update netty due to CVE-2024-29025 (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7014">KTOR-7014</a>)</li>
<li>Update dependency on swagger (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7019">KTOR-7019</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/ktorio/ktor/commit/c22735ce615a1b8d19499bff0a31d1efa8540fe6"><code>c22735c</code></a>
Release 2.3.12 (<a
href="https://redirect.github.com/ktorio/ktor/issues/4088">#4088</a>)</li>
<li>See full diff in <a
href="https://github.com/ktorio/ktor/compare/2.3.11...2.3.12">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.ktor:ktor-client-logging` from 2.3.11 to 2.3.12
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/ktorio/ktor/releases">io.ktor:ktor-client-logging's
releases</a>.</em></p>
<blockquote>
<h2>2.3.12</h2>
<blockquote>
<p>Published 20 June 2024</p>
</blockquote>
<h3>Bugfixes</h3>
<ul>
<li>NoSuchMethodError when using coroutines 1.9.0-RC (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7054">KTOR-7054</a>)</li>
<li>Server: Content-Type header for static js, css and svg resources
misses charset (<a
href="https://youtrack.jetbrains.com/issue/KTOR-6655">KTOR-6655</a>)</li>
<li>Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7016">KTOR-7016</a>)</li>
</ul>
<h3>Improvements</h3>
<ul>
<li>Update netty to 4.1.111.Final (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7094">KTOR-7094</a>)</li>
<li>Update netty due to CVE-2024-29025 (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7014">KTOR-7014</a>)</li>
<li>Update dependency on swagger (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7019">KTOR-7019</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/ktorio/ktor/blob/2.3.12/CHANGELOG.md">io.ktor:ktor-client-logging's
changelog</a>.</em></p>
<blockquote>
<h1>2.3.12</h1>
<blockquote>
<p>Published 20 June 2024</p>
</blockquote>
<h3>Bugfixes</h3>
<ul>
<li>NoSuchMethodError when using coroutines 1.9.0-RC (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7054">KTOR-7054</a>)</li>
<li>Server: Content-Type header for static js, css and svg resources
misses charset (<a
href="https://youtrack.jetbrains.com/issue/KTOR-6655">KTOR-6655</a>)</li>
<li>Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7016">KTOR-7016</a>)</li>
</ul>
<h3>Improvements</h3>
<ul>
<li>Update netty to 4.1.111.Final (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7094">KTOR-7094</a>)</li>
<li>Update netty due to CVE-2024-29025 (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7014">KTOR-7014</a>)</li>
<li>Update dependency on swagger (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7019">KTOR-7019</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/ktorio/ktor/commit/c22735ce615a1b8d19499bff0a31d1efa8540fe6"><code>c22735c</code></a>
Release 2.3.12 (<a
href="https://redirect.github.com/ktorio/ktor/issues/4088">#4088</a>)</li>
<li>See full diff in <a
href="https://github.com/ktorio/ktor/compare/2.3.11...2.3.12">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.ktor:ktor-client-content-negotiation` from 2.3.11 to 2.3.12
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/ktorio/ktor/releases">io.ktor:ktor-client-content-negotiation's
releases</a>.</em></p>
<blockquote>
<h2>2.3.12</h2>
<blockquote>
<p>Published 20 June 2024</p>
</blockquote>
<h3>Bugfixes</h3>
<ul>
<li>NoSuchMethodError when using coroutines 1.9.0-RC (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7054">KTOR-7054</a>)</li>
<li>Server: Content-Type header for static js, css and svg resources
misses charset (<a
href="https://youtrack.jetbrains.com/issue/KTOR-6655">KTOR-6655</a>)</li>
<li>Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7016">KTOR-7016</a>)</li>
</ul>
<h3>Improvements</h3>
<ul>
<li>Update netty to 4.1.111.Final (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7094">KTOR-7094</a>)</li>
<li>Update netty due to CVE-2024-29025 (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7014">KTOR-7014</a>)</li>
<li>Update dependency on swagger (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7019">KTOR-7019</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/ktorio/ktor/blob/2.3.12/CHANGELOG.md">io.ktor:ktor-client-content-negotiation's
changelog</a>.</em></p>
<blockquote>
<h1>2.3.12</h1>
<blockquote>
<p>Published 20 June 2024</p>
</blockquote>
<h3>Bugfixes</h3>
<ul>
<li>NoSuchMethodError when using coroutines 1.9.0-RC (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7054">KTOR-7054</a>)</li>
<li>Server: Content-Type header for static js, css and svg resources
misses charset (<a
href="https://youtrack.jetbrains.com/issue/KTOR-6655">KTOR-6655</a>)</li>
<li>Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7016">KTOR-7016</a>)</li>
</ul>
<h3>Improvements</h3>
<ul>
<li>Update netty to 4.1.111.Final (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7094">KTOR-7094</a>)</li>
<li>Update netty due to CVE-2024-29025 (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7014">KTOR-7014</a>)</li>
<li>Update dependency on swagger (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7019">KTOR-7019</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/ktorio/ktor/commit/c22735ce615a1b8d19499bff0a31d1efa8540fe6"><code>c22735c</code></a>
Release 2.3.12 (<a
href="https://redirect.github.com/ktorio/ktor/issues/4088">#4088</a>)</li>
<li>See full diff in <a
href="https://github.com/ktorio/ktor/compare/2.3.11...2.3.12">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.ktor:ktor-serialization-kotlinx-json` from 2.3.11 to 2.3.12
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/ktorio/ktor/releases">io.ktor:ktor-serialization-kotlinx-json's
releases</a>.</em></p>
<blockquote>
<h2>2.3.12</h2>
<blockquote>
<p>Published 20 June 2024</p>
</blockquote>
<h3>Bugfixes</h3>
<ul>
<li>NoSuchMethodError when using coroutines 1.9.0-RC (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7054">KTOR-7054</a>)</li>
<li>Server: Content-Type header for static js, css and svg resources
misses charset (<a
href="https://youtrack.jetbrains.com/issue/KTOR-6655">KTOR-6655</a>)</li>
<li>Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7016">KTOR-7016</a>)</li>
</ul>
<h3>Improvements</h3>
<ul>
<li>Update netty to 4.1.111.Final (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7094">KTOR-7094</a>)</li>
<li>Update netty due to CVE-2024-29025 (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7014">KTOR-7014</a>)</li>
<li>Update dependency on swagger (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7019">KTOR-7019</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/ktorio/ktor/blob/2.3.12/CHANGELOG.md">io.ktor:ktor-serialization-kotlinx-json's
changelog</a>.</em></p>
<blockquote>
<h1>2.3.12</h1>
<blockquote>
<p>Published 20 June 2024</p>
</blockquote>
<h3>Bugfixes</h3>
<ul>
<li>NoSuchMethodError when using coroutines 1.9.0-RC (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7054">KTOR-7054</a>)</li>
<li>Server: Content-Type header for static js, css and svg resources
misses charset (<a
href="https://youtrack.jetbrains.com/issue/KTOR-6655">KTOR-6655</a>)</li>
<li>Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7016">KTOR-7016</a>)</li>
</ul>
<h3>Improvements</h3>
<ul>
<li>Update netty to 4.1.111.Final (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7094">KTOR-7094</a>)</li>
<li>Update netty due to CVE-2024-29025 (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7014">KTOR-7014</a>)</li>
<li>Update dependency on swagger (<a
href="https://youtrack.jetbrains.com/issue/KTOR-7019">KTOR-7019</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/ktorio/ktor/commit/c22735ce615a1b8d19499bff0a31d1efa8540fe6"><code>c22735c</code></a>
Release 2.3.12 (<a
href="https://redirect.github.com/ktorio/ktor/issues/4088">#4088</a>)</li>
<li>See full diff in <a
href="https://github.com/ktorio/ktor/compare/2.3.11...2.3.12">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>