Bump com.google.devtools.ksp from 2.0.0-1.0.21 to 2.0.0-1.0.22 (#424)
Bumps [com.google.devtools.ksp](https://github.com/google/ksp) from
2.0.0-1.0.21 to 2.0.0-1.0.22.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/google/ksp/releases">com.google.devtools.ksp's
releases</a>.</em></p>
<blockquote>
<h2>2.0.0-1.0.22</h2>
<h2>Important Changes</h2>
<ul>
<li><code>KSErrorType.toString()</code> now contains the reference name
it was tried to be resolved, and therefore <code>KSErrorType</code> is
no longer a singleton. Processors relying on equality checks of that (in
contrast of using <code>KSType.isError</code>) will need to be updated
accordingly.</li>
</ul>
<h2>Issues Fixed</h2>
<p><a
href="https://redirect.github.com/google/ksp/issues/1908">#1908</a>
KSP2: Calling KSP2 in programs does not appear to work on macOS or
Windows
<a href="https://redirect.github.com/google/ksp/issues/1917">#1917</a>
KSP2's symbol-processing-aa-embeddable artifact exposes an unresolvable
pre-release kotlin 2.0.20 dependency
<a href="https://redirect.github.com/google/ksp/issues/1911">#1911</a>
NoSuchMethodError when running KSP2 with Dagger (KSP 2.0.0-1.0.21)
<a href="https://redirect.github.com/google/ksp/issues/1909">#1909</a>
KSP2: default annotation arguments no longer work in 1.0.21
<a href="https://redirect.github.com/google/ksp/issues/1232">#1232</a>
Expose simple names on a missing types's synthetic declaration
<a href="https://redirect.github.com/google/ksp/issues/1857">#1857</a>
[KSP2] Modifiers are missing for property accessors
<a href="https://redirect.github.com/google/ksp/issues/1924">#1924</a>
[KSP2] Type arg becomes '*' after calling KSType.replace() with an error
type
<a href="https://redirect.github.com/google/ksp/issues/1948">#1948</a>
KSP2 default annotation KClass values for built-in types use java.lang.*
versions</p>
<h2>What's Changed</h2>
<ul>
<li>Include type hint into KSErrorType. by <a
href="https://github.com/Jeffset"><code>@​Jeffset</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1848">google/ksp#1848</a></li>
<li>Implement Resolver.getModuleName API by <a
href="https://github.com/ZacSweers"><code>@​ZacSweers</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1847">google/ksp#1847</a></li>
<li>Patch AA service files in renamed uber jar by <a
href="https://github.com/ting-yuan"><code>@​ting-yuan</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1867">google/ksp#1867</a></li>
<li>fix annotation default value parsing for arrays and class literals.
by <a href="https://github.com/neetopia"><code>@​neetopia</code></a> in
<a
href="https://redirect.github.com/google/ksp/pull/1871">google/ksp#1871</a></li>
<li>fix package name for library based symbols by <a
href="https://github.com/neetopia"><code>@​neetopia</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1873">google/ksp#1873</a></li>
<li>Do not index classpath in declaration provider by <a
href="https://github.com/ting-yuan"><code>@​ting-yuan</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1870">google/ksp#1870</a></li>
<li>check functional interface for modifiers by <a
href="https://github.com/neetopia"><code>@​neetopia</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1872">google/ksp#1872</a></li>
<li>Annotation default java by <a
href="https://github.com/neetopia"><code>@​neetopia</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1879">google/ksp#1879</a></li>
<li>fix type parameter bounds by <a
href="https://github.com/neetopia"><code>@​neetopia</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1880">google/ksp#1880</a></li>
<li>Add command line parser and entry points by <a
href="https://github.com/ting-yuan"><code>@​ting-yuan</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1885">google/ksp#1885</a></li>
<li>KSP2: Fix support of wasm by <a
href="https://github.com/ting-yuan"><code>@​ting-yuan</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1888">google/ksp#1888</a></li>
<li>Return KSClassDeclarationEnumEntryImpl for enum entry annotation
values. by <a
href="https://github.com/neetopia"><code>@​neetopia</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1881">google/ksp#1881</a></li>
<li>Reuse Kotlin indexes in incremental providers by <a
href="https://github.com/ting-yuan"><code>@​ting-yuan</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1891">google/ksp#1891</a></li>
<li>special handling for java property accessors override checking by <a
href="https://github.com/neetopia"><code>@​neetopia</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1894">google/ksp#1894</a></li>
<li>KSP2: Reuse Java indexes by <a
href="https://github.com/ting-yuan"><code>@​ting-yuan</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1895">google/ksp#1895</a></li>
<li>Incremental: fix roots from getSealedSubclasses by <a
href="https://github.com/ting-yuan"><code>@​ting-yuan</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1893">google/ksp#1893</a></li>
<li>use safe cast for annotation type to declaration resolution by <a
href="https://github.com/neetopia"><code>@​neetopia</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/1902">google/ksp#1902</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/google/ksp/compare/2.0.0-1.0.21...2.0.0-1.0.22">https://github.com/google/ksp/compare/2.0.0-1.0.21...2.0.0-1.0.22</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/google/ksp/commit/1ac3fd8f8915c9674e520709033e92d3df0b94f2"><code>1ac3fd8</code></a>
CI: auto-merge: rebase again before push</li>
<li><a
href="https://github.com/google/ksp/commit/414d37a6731c9cb869d53a51b80ca81c10e86a4a"><code>414d37a</code></a>
CI: enable manual trigger</li>
<li><a
href="https://github.com/google/ksp/commit/eaf9f7a74ecddcdbd89112c2a3aa83bb1c2c67c5"><code>eaf9f7a</code></a>
map java types to kotlin types when parsing annotation class reference
values</li>
<li><a
href="https://github.com/google/ksp/commit/893a784a9917a153022827295029469290ecd59d"><code>893a784</code></a>
Update ksp2entrypoints.md</li>
<li><a
href="https://github.com/google/ksp/commit/0c639834ce9489218539c920a32c0dc153673231"><code>0c63983</code></a>
Update ksp2entrypoints.md</li>
<li><a
href="https://github.com/google/ksp/commit/f08bc85a0243c66e6dcf3d2f3efd93085bb8c1b0"><code>f08bc85</code></a>
DeclarationProvider: skip builtins when possible.</li>
<li><a
href="https://github.com/google/ksp/commit/76bf45dacece9c0e3afa518d0ab070ebff7175cf"><code>76bf45d</code></a>
Make originalAnnotations lazy</li>
<li><a
href="https://github.com/google/ksp/commit/e34a635819d236913cff2677033a44b6ffc5a17a"><code>e34a635</code></a>
fix property accessor modifier logic</li>
<li><a
href="https://github.com/google/ksp/commit/82871d85ebc79d0f1747384820379e45546691fb"><code>82871d8</code></a>
Provide more hints for error types.</li>
<li><a
href="https://github.com/google/ksp/commit/c77e1702f7ba931f49b767dcb98dfc84f57540b4"><code>c77e170</code></a>
<a href="https://redirect.github.com/google/ksp/issues/1232">#1232</a>:
Include type hint into KSErrorType.</li>
<li>Additional commits viewable in <a
href="https://github.com/google/ksp/compare/2.0.0-1.0.21...2.0.0-1.0.22">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.google.devtools.ksp&package-manager=gradle&previous-version=2.0.0-1.0.21&new-version=2.0.0-1.0.22)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>