Bump org.jetbrains.kotlinx:kotlinx-serialization-json from 1.5.0 to 1.5.1 (#40)
Bumps
[org.jetbrains.kotlinx:kotlinx-serialization-json](https://github.com/Kotlin/kotlinx.serialization)
from 1.5.0 to 1.5.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/Kotlin/kotlinx.serialization/releases">org.jetbrains.kotlinx:kotlinx-serialization-json's
releases</a>.</em></p>
<blockquote>
<h2>1.5.1</h2>
<p>This release contains an important Native targets overhaul, as well
as numerous enhancements and bugfixes.
Kotlin 1.8.21 is used by default.</p>
<h3>New set of Native targets</h3>
<p>The official <a
href="https://kotlinlang.org/docs/native-target-support.html">Kotlin
target support policy</a> has recently been published describing new
target policy: each target belongs to a certain <em>tier</em>, and
different tiers have different stability guarantees. The official
recommendation for library authors is to support targets up to Tier 3,
and kotlinx.serialization now follows it. It means that in this release,
there are a lot of new targets added from this tier, such as
<code>androidNativeX86</code> or <code>watchosDeviceArm64</code>. Note
that since they belong to Tier 3, they're not auto-tested on CI.</p>
<p>kotlinx.serialization also ships some deprecated Kotlin/Native
targets that do not belong to any tier (e.g. <code>iosArm32</code>,
<code>mingwX86</code>).
We'll continue to release them, but we do not provide support for them,
nor do we plan to add new targets from the deprecated list.</p>
<h3>Improvements in Json elements</h3>
<p>There are two new function sets that should make creating raw Json
elements easier.
<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/pull/2160">First
one</a> contains overloads for <code>JsonPrimitive</code>
constructor-like function that accept unsigned types:
<code>JsonPrimitive(1u)</code>.
<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/pull/2156">Second
one</a> adds new <code>addAll</code> functions to
<code>JsonArrayBuilder</code> to be used with collections of numbers,
booleans or strings: <code>buildJsonArray { addAll(listOf(1, 2, 3))
}</code>.
Both were contributed to us by <a
href="https://github.com/aSemy">aSemy</a>.</p>
<h3>Other enhancements</h3>
<ul>
<li><strong>Potential source-breaking change</strong>: Rename json-okio
<code>target</code> variables to <code>sink</code> (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2226">#2226</a>)</li>
<li>Function to retrieve KSerializer by KClass and type arguments
serializers (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2291">#2291</a>)</li>
<li>Added FormatLanguage annotation to Json methods (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2234">#2234</a>)</li>
<li>Properties Format: Support sealed/polymorphic classes as class
properties (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2255">#2255</a>)</li>
</ul>
<h3>Bugfixes</h3>
<ul>
<li>KeyValueSerializer: Fix missing call to endStructure() (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2272">#2272</a>)</li>
<li>ObjectSerializer: Respect sequential decoding (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2273">#2273</a>)</li>
<li>Fix value class encoding in various corner cases (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2242">#2242</a>)</li>
<li>Fix incorrect json decoding iterator's .hasNext() behavior on
array-wrapped inputs (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2268">#2268</a>)</li>
<li>Fix memory leak caused by invalid KTypeWrapper's equals method (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2274">#2274</a>)</li>
<li>Fixed NoSuchMethodError when parsing a JSON stream on Java 8 (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2219">#2219</a>)</li>
<li>Fix MissingFieldException duplication (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2213">#2213</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md">org.jetbrains.kotlinx:kotlinx-serialization-json's
changelog</a>.</em></p>
<blockquote>
<h1>1.5.1 / 2023-05-11</h1>
<p>This release contains an important Native targets overhaul, as well
as numerous enhancements and bugfixes.
Kotlin 1.8.21 is used by default.</p>
<h3>New set of Native targets</h3>
<p>The official <a
href="https://kotlinlang.org/docs/native-target-support.html">Kotlin
target support policy</a> has recently been published
describing new target policy: each target belongs to a certain
<em>tier</em>, and different tiers have different stability guarantees.
The official recommendation for library authors is to support targets up
to Tier 3,
and kotlinx.serialization now follows it.
It means that in this release, there are a lot of new targets added from
this tier,
such as <code>androidNativeX86</code> or
<code>watchosDeviceArm64</code>.
Note that since they belong to Tier 3, they're not auto-tested on
CI.</p>
<p>kotlinx.serialization also ships some deprecated Kotlin/Native
targets that do not belong to any tier (e.g. <code>iosArm32</code>,
<code>mingwX86</code>).
We'll continue to release them, but we do not provide support for them,
nor do we plan to add new targets from the deprecated list.</p>
<h3>Improvements in Json elements</h3>
<p>There are two new function sets that should make creating raw Json
elements easier.
<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/pull/2160">First
one</a> contains overloads for <code>JsonPrimitive</code>
constructor-like function
that accept unsigned types: <code>JsonPrimitive(1u)</code>.
<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/pull/2156">Second
one</a> adds new <code>addAll</code> functions to
<code>JsonArrayBuilder</code> to be used with collections
of numbers, booleans or strings: <code>buildJsonArray { addAll(listOf(1,
2, 3)) }</code>
Both were contributed to us by <a
href="https://github.com/aSemy">aSemy</a>.</p>
<h3>Other enhancements</h3>
<ul>
<li><strong>Potential source-breaking change</strong>: Rename json-okio
<code>target</code> variables to <code>sink</code> (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2226">#2226</a>)</li>
<li>Function to retrieve KSerializer by KClass and type arguments
serializers (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2291">#2291</a>)</li>
<li>Added FormatLanguage annotation to Json methods (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2234">#2234</a>)</li>
<li>Properties Format: Support sealed/polymorphic classes as class
properties (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2255">#2255</a>)</li>
</ul>
<h3>Bugfixes</h3>
<ul>
<li>KeyValueSerializer: Fix missing call to endStructure() (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2272">#2272</a>)</li>
<li>ObjectSerializer: Respect sequential decoding (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2273">#2273</a>)</li>
<li>Fix value class encoding in various corner cases (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2242">#2242</a>)</li>
<li>Fix incorrect json decoding iterator's .hasNext() behavior on
array-wrapped inputs (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2268">#2268</a>)</li>
<li>Fix memory leak caused by invalid KTypeWrapper's equals method (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2274">#2274</a>)</li>
<li>Fixed NoSuchMethodError when parsing a JSON stream on Java 8 (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2219">#2219</a>)</li>
<li>Fix MissingFieldException duplication (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2213">#2213</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/f83385276ce63fd8f76ce333a6f43ec095e9a1da"><code>f833852</code></a>
Prepare 1.5.1 release (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2297">#2297</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/a27e86f7aa71eeb482da99e32e8a131e2d484daa"><code>a27e86f</code></a>
Function to retrieve KSerializer by KClass and type arguments
serializers (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2">#2</a>...</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/5a8795a9c6a287c0479190c6abc8a46f5e003d37"><code>5a8795a</code></a>
Added FormatLanguage annotation to JSON (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2234">#2234</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/40eb27758b374d38a8444699eb766f8e4b9761f9"><code>40eb277</code></a>
Merge remote-tracking branch 'origin/master' into dev</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/9157bf81283ad3d1b4313873bc81150af2f69a4f"><code>9157bf8</code></a>
Implement addAll functions for JsonArrayBuilder (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2156">#2156</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/ef67bcef0e5ee8ef0d19a3d9dcbb08e82a92c511"><code>ef67bce</code></a>
KeyValueSerializer: Fix missing call to endStructure() (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2272">#2272</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/80075749139be1144a4cd5dd9d32cfbf261ee975"><code>8007574</code></a>
ObjectSerializer: Respect sequential decoding (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2273">#2273</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/0a6eb817c5cf4fa84ab8d360060934a1c74820be"><code>0a6eb81</code></a>
Fix incorrect function name in PrimitiveSerialDescriptor doc comment (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2289">#2289</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/cfce5d8bf4e24fd6a1caf2cef9f62dd689614ce5"><code>cfce5d8</code></a>
Properties Format: Support sealed/polymorphic classes as class
properties (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2">#2</a>...</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/961e87d492276e9dd73d55867e766108195287ed"><code>961e87d</code></a>
Adapt tests for K2 and upcoming deprecations in K1 (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2230">#2230</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/Kotlin/kotlinx.serialization/compare/v1.5.0...v1.5.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlinx:kotlinx-serialization-json&package-manager=gradle&previous-version=1.5.0&new-version=1.5.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>